spring:
  application:
    name: telecom-demo-backend
  datasource:
    url: jdbc:sqlite:app.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: false
